name: Bukubook Test

on: [push]

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: bukubook
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Install composer dependencies
        run: composer install -n --prefer-dist
      - name: Run Static Analysis
        run: ./vendor/bin/phpstan --error-format=github
      - name: Create env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Generate env key
        run: php artisan key:generate
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Migrate
        run: php artisan migrate --seed
      - name: Install Front-end
        run: |
          npm install
          npm run build
      - name: Feature Test
        run: php artisan test
